FROM ubuntu

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    && apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
    && apt-get install -y python python-pip\
    && pip install awscli --upgrade


RUN mkdir /src

WORKDIR /src

ADD ./ /src

CMD ["/bin/bash"]